waypoint_reconfigure_config:
  version: 1.0.0
  name: "description"
  default_dwa_limit_vel: 1.0
  default_local_inflation: 0.4
  default_global_inflation: 0.4
  areas:
    - name: "elevator1"
      start_id: registed_0_144860000000
      end_id: registed_0_155612000000
      properties:
        - key: global_inflation
          value: 0.2
        - key: local_inflation
          value: 0.2
        - key: dwa_limit_vel
          value: 0.5
    - name: "elevator2"
      start_id: registed_0_108807000000
      end_id: registed_0_144860000000
      properties:
        - key: global_inflation
          value: 0.2
        - key: local_inflation
          value: 0.2
        - key: dwa_limit_vel
          value: 0.5