waypoint_reconfigure_config:
  version: 1.0.0
  name: "description"
  default_dwa_limit_vel: 0.8
  default_local_inflation: 0.2
  default_global_inflation: 10.0
  areas:
    - name: "elevator1"
      start_id: registed_0_1299399000000
      end_id: registed_0_57914000000
      properties:
        - key: global_inflation
          value: 0.4
        - key: local_inflation
          value: 0.2
        - key: dwa_limit_vel
          value: 0.5
